export const COUNTRIES = [
  { code: 'US', flag: '🇺🇸', dial: '+1', name: 'United States' },
  { code: 'GB', flag: '🇬🇧', dial: '+44', name: 'United Kingdom' },
  { code: 'CA', flag: '🇨🇦', dial: '+1', name: 'Canada' },
  { code: 'AU', flag: '🇦🇺', dial: '+61', name: 'Australia' },
  { code: 'DE', flag: '🇩🇪', dial: '+49', name: 'Germany' },
  { code: 'FR', flag: '🇫🇷', dial: '+33', name: 'France' },
  { code: 'ES', flag: '🇪🇸', dial: '+34', name: 'Spain' },
  { code: 'IT', flag: '🇮🇹', dial: '+39', name: 'Italy' },
  { code: 'PT', flag: '🇵🇹', dial: '+351', name: 'Portugal' },
  { code: 'BR', flag: '🇧🇷', dial: '+55', name: 'Brazil' },
  { code: 'AR', flag: '🇦🇷', dial: '+54', name: 'Argentina' },
  { code: 'MX', flag: '🇲🇽', dial: '+52', name: 'Mexico' },
  { code: 'CO', flag: '🇨🇴', dial: '+57', name: 'Colombia' },
  { code: 'CL', flag: '🇨🇱', dial: '+56', name: 'Chile' },
  { code: 'PE', flag: '🇵🇪', dial: '+51', name: 'Peru' },
  { code: 'JP', flag: '🇯🇵', dial: '+81', name: 'Japan' },
  { code: 'KR', flag: '🇰🇷', dial: '+82', name: 'South Korea' },
  { code: 'CN', flag: '🇨🇳', dial: '+86', name: 'China' },
  { code: 'IN', flag: '🇮🇳', dial: '+91', name: 'India' },
  { code: 'TH', flag: '🇹🇭', dial: '+66', name: 'Thailand' },
  { code: 'PH', flag: '🇵🇭', dial: '+63', name: 'Philippines' },
  { code: 'VN', flag: '🇻🇳', dial: '+84', name: 'Vietnam' },
  { code: 'ID', flag: '🇮🇩', dial: '+62', name: 'Indonesia' },
  { code: 'MY', flag: '🇲🇾', dial: '+60', name: 'Malaysia' },
  { code: 'SG', flag: '🇸🇬', dial: '+65', name: 'Singapore' },
  { code: 'NG', flag: '🇳🇬', dial: '+234', name: 'Nigeria' },
  { code: 'ZA', flag: '🇿🇦', dial: '+27', name: 'South Africa' },
  { code: 'EG', flag: '🇪🇬', dial: '+20', name: 'Egypt' },
  { code: 'KE', flag: '🇰🇪', dial: '+254', name: 'Kenya' },
  { code: 'MA', flag: '🇲🇦', dial: '+212', name: 'Morocco' },
  { code: 'TN', flag: '🇹🇳', dial: '+216', name: 'Tunisia' },
  { code: 'DZ', flag: '🇩🇿', dial: '+213', name: 'Algeria' },
  { code: 'TR', flag: '🇹🇷', dial: '+90', name: 'Turkey' },
  { code: 'SA', flag: '🇸🇦', dial: '+966', name: 'Saudi Arabia' },
  { code: 'AE', flag: '🇦🇪', dial: '+971', name: 'UAE' },
  { code: 'IL', flag: '🇮🇱', dial: '+972', name: 'Israel' },
  { code: 'RU', flag: '🇷🇺', dial: '+7', name: 'Russia' },
  { code: 'UA', flag: '🇺🇦', dial: '+380', name: 'Ukraine' },
  { code: 'PL', flag: '🇵🇱', dial: '+48', name: 'Poland' },
  { code: 'NL', flag: '🇳🇱', dial: '+31', name: 'Netherlands' },
  { code: 'SE', flag: '🇸🇪', dial: '+46', name: 'Sweden' },
  { code: 'NO', flag: '🇳🇴', dial: '+47', name: 'Norway' },
  { code: 'DK', flag: '🇩🇰', dial: '+45', name: 'Denmark' },
  { code: 'FI', flag: '🇫🇮', dial: '+358', name: 'Finland' },
  { code: 'IE', flag: '🇮🇪', dial: '+353', name: 'Ireland' },
  { code: 'NZ', flag: '🇳🇿', dial: '+64', name: 'New Zealand' },
  { code: 'GR', flag: '🇬🇷', dial: '+30', name: 'Greece' },
  { code: 'CH', flag: '🇨🇭', dial: '+41', name: 'Switzerland' },
  { code: 'AT', flag: '🇦🇹', dial: '+43', name: 'Austria' },
  { code: 'BE', flag: '🇧🇪', dial: '+32', name: 'Belgium' },
  { code: 'CZ', flag: '🇨🇿', dial: '+420', name: 'Czech Republic' },
  { code: 'RO', flag: '🇷🇴', dial: '+40', name: 'Romania' },
  { code: 'PK', flag: '🇵🇰', dial: '+92', name: 'Pakistan' },
  { code: 'BD', flag: '🇧🇩', dial: '+880', name: 'Bangladesh' },
  { code: 'LK', flag: '🇱🇰', dial: '+94', name: 'Sri Lanka' },
  { code: 'NP', flag: '🇳🇵', dial: '+977', name: 'Nepal' },
];
